version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies if any..."
  build:
    commands:
      - echo "Building static files (none required for HTML/CSS/JS)"
artifacts:
  files:
    - '**/*'
  discard-paths: no

